
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: senaffairs_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: senaffairs
  password: boomboom0


test:
  <<: *default
  database: senaffairs_test


production:
  <<: *default
  database: senaffairs_production
  username: <%= ENV['deploy'] %>
  password: <%= ENV['boomboom0'] %>
